### ISSUE TITLE
Use ChannelHandlerAdapter instead of ChannelInboundHandlerAdapter in HttpRouterHandler

### ISSUE THREAD

**Issue by joeltjarnstig** [hi3g/opentsdb#142]
Netty documentation claims ChannelInboundHandlerAdapter is deprecated and we should use ChannelHandlerAdapter instead.

<li>http://netty.io/5.0/api/io/netty/channel/ChannelInboundHandlerAdapter.html</li>

**Comment by luuse** [comment]
We're currently using Netty 4.1.Beta5 and `ChannelInboundHandlerAdapter` seems to only be deprecated in 5.0 and onward. @joeltjarnstig would it be hard to switch to `ChannelHandlerAdapter` now?

**Comment by joeltjarnstig** [comment]
It would be very easy to change to ChannelHandlerAdapter, but unnecessary since even if we make the changes, code still has to be modified when/if we upgrade to netty  5.0.

**Comment by luuse** [comment]
Unless there are any downsides to doing this now i suggest we still make the change now so we don't have to bother later?

**Comment by luuse** [comment]
We can't make the switch yet since `ChannelHandlerAdapter` doesn't give us a way to read messages so we're postponing this for a potential upgrade to Netty 5.
