### ISSUE TITLE
Const.MAX_TIMESPAN is in seconds but we assume it is in milliseconds throughout the program

### ISSUE THREAD

**Issue by Kasidro** [hi3g/opentsdb#146]

**Comment by luuse** [comment]
We should fix this by only requiring that `timestamp > 0` in `net.opentsdb.core.DataPointsClient#checkTimestamp`. When this is done `net.opentsdb.core.Const#MAX_MS_TIMESTAMP` and `net.opentsdb.core.Const#SECOND_MASK` should be removed as well. `net.opentsdb.core.Const#MAX_TIMESPAN` Should be moved into `net.opentsdb.storage.cassandra.CassandraConst`.
