### ISSUE TITLE
Call call super.setupModule(context) in JacksonModule

### ISSUE THREAD

**Issue by joeltjarnstig** [hi3g/opentsdb#159]
We should call super.setupModule(context) if we want to override this method.
see: <li>https://fasterxml.github.io/jackson-databind/javadoc/2.4/com/fasterxml/jackson/databind/module/SimpleModule.html</li>

**Comment by luuse** [comment]
Maybe we should stop overriding that method and instead use the setters and add methods in the constructor instead?

**Comment by luuse** [comment]
^ Seems to be how the jackson developers intends users to consume it?

**Comment by joeltjarnstig** [comment]
That is true. I will investigate this

**Comment by luuse** [comment]
Fixed in #163
