### ISSUE TITLE
Timespan check in Metaclient#deleterange needs to be fixed

### ISSUE THREAD

**Issue by Kasidro** [hi3g/opentsdb#166]
we do not use the timestamp class to check the timespan in the deleteRange method of MetaClient as it has different constrictions on endtime (can't be undifined, -1,  in this case).

**Comment by luuse** [comment]
We should probably think over this a bit more. It is probably a good idea to have two different classes that separates these two different time types. One for instants and one for time periods. The time range class could additionally handle open and closed ranges.

**Comment by Kasidro** [comment]
fixed in #162
